name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          script: |
            cd /opt/AI-Quiz-App

            # Pull latest code
            git pull

            # Frontend
            cd frontend
            npm install
            npm run build

            # Backend
            cd ..
            source backend/venv/bin/activate
            pip install -r requirements.txt

            # Restart backend service
            systemctl restart backend
