name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          script: |
            cd /opt/AI-Quiz-App
            git pull
            cd frontend
            npm install
            npm run build
            cd ../backend
            source venv/bin/activate
            pip install -r requirements.txt
            systemctl restart backend
