name: Run Postman tests and deploy to droplet

on:
  push:
    branches:
      - main

jobs:
  # Run Postman API tests before deploying
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        run: |
          newman run tests/postman/collection.json \
          -e tests/postman/environment.json \
          --reporters cli,junit \
          --reporter-junit-export results.xml

      - name: Upload Newman results
        uses: actions/upload-artifact@v4
        with:
          name: newman-results
          path: results.xml

  # Deploy only if tests succeed
  deploy:
    runs-on: ubuntu-latest
    needs: api-tests   # deploy waits for API tests to pass

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          script: |
            cd /opt/AI-Quiz-App

            # Pull latest code
            git pull

            # Frontend
            cd frontend
            npm install
            npm run build

            # Backend
            cd ..
            source backend/venv/bin/activate
            pip install -r requirements.txt

            # Restart backend service
            systemctl restart backend
